USE Accidentes;

DROP TABLE IF EXISTS Comunas;


CREATE TABLE IF NOT EXISTS Comunas(
ID INT PRIMARY KEY,
POB_COMUNA INT,
CANT_LOC INT,
TOTAL_HOMICIDIOS INT,
DENSIDAD_HOMICIDIOS DECIMAL(10,6)
);
LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.3\\Uploads\\comunasSQL.csv'
INTO TABLE Comunas
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM comunas;

DROP TABLE IF EXISTS Homicidios;


CREATE TABLE IF NOT EXISTS Homicidios (
ID INT PRIMARY KEY,
NUM_VICTIMAS INT,
FECHA DATE,
HORA TIME,
HH FLOAT,
TIPO_CALLE VARCHAR(256),
CALLE VARCHAR(256),
LUGAR_HECHO_NORM TEXT,
COMUNA INT,
LONGITUD DECIMAL(10,8),
LATITU DECIMAL (10,8),
VICTIMA VARCHAR (100),
ACUSADO VARCHAR (100),
SEXO VARCHAR(20),
EDAD INT,
ROL_VICTIMA VARCHAR(30),
AÑO YEAR,
MES INT,
DIA_SEMANA VARCHAR(20),
FOREIGN KEY (COMUNA) REFERENCES Comunas(ID)
);
LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.3\\Uploads\\homicidiosSQL.csv'
INTO TABLE Homicidios
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM Homicidios;








