DROP DATABASE IF EXISTS	Accidentes;


CREATE DATABASE IF NOT EXISTS Accidentes;

USE Accidentes;


DROP TABLE IF EXISTS Comunas;


CREATE TABLE IF NOT EXISTS Comunas(
ID INT PRIMARY KEY,
POB_COMUNAx1000 DECIMAL(6,3),
CANT_LOC INT
);
LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.3\\Uploads\\comunas.csv'
INTO TABLE Comunas
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n'
IGNORE 1 ROWS;



DROP TABLE IF EXISTS Homicidios;


CREATE TABLE IF NOT EXISTS Homicidios (
ID INT PRIMARY KEY,
NUM_VICTIMAS INT,
FECHA DATE,
HORA TIME,
HH FLOAT,
TIPO_CALLE VARCHAR(256),
CALLE VARCHAR(256),
LUGAR_HECHO_NORM TEXT,
COMUNA INT,
LONGITUD DECIMAL(10,8),
LATITU DECIMAL (10,8),
VICTIMA VARCHAR (100),
ACUSADO VARCHAR (100),
SEXO VARCHAR(20),
EDAD INT,
ROL_VICTIMA VARCHAR(30),
FOREIGN KEY (COMUNA) REFERENCES Comunas(ID)
);
LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.3\\Uploads\\homicidios.csv'
INTO TABLE Homicidios
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM Homicidios;

DROP TABLE IF EXISTS Lesiones;

SHOW VARIABLES LIKE 'secure_file_priv';


CREATE TABLE IF NOT EXISTS Lesiones(
ID VARCHAR(20) NOT NULL PRIMARY KEY,
CANT_VICTIMAS INT,
FECHA DATE,
HORA TIME,
HH INT,
COMUNA INT,
TIPO_CALLE VARCHAR(256),
DIREC_NORMALIZADA VARCHAR(256),
LONGITUD DECIMAL(10,8),
LATITUD DECIMAL(10,8),
VICTIMA VARCHAR(100),
ACUSADO VARCHAR(100),
GRAVEDAD VARCHAR(100),
FOREIGN KEY (COMUNA) REFERENCES Comunas(ID)
);


LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.3\\Uploads\\lesiones.csv'
INTO TABLE Lesiones
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
IGNORE 1 ROWS;


SELECT * FROM Lesiones;

